name: Publish Package to npm
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      # Check if version has changed
      - name: Check version changes
        id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: package.json
          
      # Publish only if version has changed
      - if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          
      - if: steps.check.outputs.changed == 'true'
        run: npm ci
        
      - if: steps.check.outputs.changed == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 